---
  - name: Enable Puppet 5 repository
    yum: 
      name: https://yum.puppetlabs.com/puppet5/puppet5-release-el-7.noarch.rpm
      state: present
    tags:
      - prereq_enable_repository
      - prereq_enable_repository_rhel_base

  - name: Enable EPEL 7 repository
    yum: 
      name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: present
    tags:
      - prereq_enable_repository
      - prereq_enable_repository_rhel_base

  - name: Enable Foreman repository
    yum: 
      name: https://yum.theforeman.org/releases/1.16/el7/x86_64/foreman-release.rpm
      state: present
    tags:
      - prereq_enable_repository
      - prereq_enable_repository_rhel_base

  - name: Update Red Hat system to the latest version
    yum:
      name: "*"
      state: latest
    tags:
      - prereq_enable_repository
      - prereq_enable_repository_rhel_base

# vim:sw=2:ts=2:et:
