---
# create devops and configure wheel via sudoers without password
- import_tasks: ../tasks/_prep-create-devops-user-sudo.yml

# make sure SELinux is enforcing
- import_tasks: ../tasks/_prep-selinux-enforcing.yml

# Enable all repos used in the Foreman installation
- import_tasks: ../tasks/_prep-repos.yml


# vim:sw=2:ts=2:et:
